set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
if(NOT DEFINED ENV{ARM_GCC_BIN})
  message(FATAL_ERROR "Set ARM_GCC_BIN to the pinned arm-none-eabi toolchain bin directory")
endif()
set(CMAKE_C_COMPILER "$ENV{ARM_GCC_BIN}/arm-none-eabi-gcc")
set(CMAKE_ASM_COMPILER "${CMAKE_C_COMPILER}")
set(CMAKE_OBJCOPY "$ENV{ARM_GCC_BIN}/arm-none-eabi-objcopy")
set(CMAKE_SIZE "$ENV{ARM_GCC_BIN}/arm-none-eabi-size")
